FROM maven:3.8.7-amazoncorretto-19

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG GRAAL_JAVA_VERSION=19
ARG GRAAL_VERSION=22.3.0
ARG INSTALL_PKGS="gzip"

RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM" > /log
#ENV GRAAL_PLATFORM=$(expr substr "${TARGETPLATFORM}"0 :5)
#ENV GRAAL_ARCH=${TARGETPLATFORM:6}

RUN echo "export GRAAL_PLATFORM=${TARGETPLATFORM:0:5};export GRAAL_ARCH=${TARGETPLATFORM:6};" >> /envfile
#RUN . /envfile1; echo $GRAAL_PLATFORM
#RUN echo "export GRAAL_ARCH=${TARGETPLATFORM:6}" >> /envfile2
RUN sed -i 's/arm64/aarch64/g' /envfile
#RUN . /envfile2; echo $GRAAL_ARCH
RUN . /envfile; echo "I am building for $GRAAL_PLATFORM + $GRAAL_ARCH"

#ENV GRAAL_CE_URL=https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-java${GRAAL_JAVA_VERSION}-${GRAAL_PLATFORM}-${GRAAL_ARCH}-${GRAAL_VERSION}.tar.gz
#RUN . /envfile; echo "GRAAL_JAVA_VERSION=$GRAAL_JAVA_VERSION,GRAAL_PLATFORM=${GRAAL_PLATFORM}, GRAAL_ARCH=$GRAAL_ARCH, GRAAL_VERSION=$GRAAL_VERSION, GRAAL_CE_URL=$GRAAL_CE_URL" > /log

RUN . /envfile; echo "export GRAAL_CE_URL=https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${GRAAL_VERSION}/graalvm-ce-java${GRAAL_JAVA_VERSION}-${GRAAL_PLATFORM}-${GRAAL_ARCH}-${GRAAL_VERSION}.tar.gz;" > envfile;
RUN . /envfile; echo "GRAAL_PLATFORM=$GRAAL_PLATFORM, GRAAL_ARCH=$GRAAL_ARCH, GRAAL_CE_URL=${GRAAL_CE_URL}"
run . /envfile; curl "${GRAAL_CE_URL}"

ENV GRAALVM_HOME /opt/graalvm
ENV JAVA_HOME /opt/graalvm

RUN mkdir -p ${GRAALVM_HOME} && \
	 cd ${GRAALVM_HOME} && \
	 . /envfile; curl -fsSL ${GRAAL_CE_URL} | tar -xzC ${GRAALVM_HOME} --strip-components=1  && \
     ### Cleanup
     yum clean all && \
     . /envfile; rm -f /tmp/graalvm-ce-${GRAAL_ARCH}.tar.gz && \
     rm -rf /var/cache/yum
     ###